"""Add new models for saved itineraries, reviews, collaboration, flights, and accommodations

Revision ID: 631d33b60e28
Revises: 
Create Date: 2026-01-04 15:47:06.802240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631d33b60e28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_itineraries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('city_ids', sa.JSON(), nullable=False),
    sa.Column('trip_data', sa.JSON(), nullable=False),
    sa.Column('itinerary_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_itineraries_created_at'), 'saved_itineraries', ['created_at'], unique=False)
    op.create_index(op.f('ix_saved_itineraries_is_public'), 'saved_itineraries', ['is_public'], unique=False)
    op.create_index(op.f('ix_saved_itineraries_session_id'), 'saved_itineraries', ['session_id'], unique=False)
    op.create_index(op.f('ix_saved_itineraries_share_token'), 'saved_itineraries', ['share_token'], unique=True)
    op.create_table('accommodations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('avg_price_per_night', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accommodations_avg_price_per_night'), 'accommodations', ['avg_price_per_night'], unique=False)
    op.create_index(op.f('ix_accommodations_category'), 'accommodations', ['category'], unique=False)
    op.create_index(op.f('ix_accommodations_city_id'), 'accommodations', ['city_id'], unique=False)
    op.create_index(op.f('ix_accommodations_id'), 'accommodations', ['id'], unique=False)
    op.create_table('collaboration_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('itinerary_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_session', sa.String(length=255), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['saved_itineraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_sessions_expires_at'), 'collaboration_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_collaboration_sessions_session_token'), 'collaboration_sessions', ['session_token'], unique=True)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_city_id', sa.Integer(), nullable=False),
    sa.Column('destination_city_id', sa.Integer(), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=True),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('avg_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['destination_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['origin_city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_destination_city_id'), 'flights', ['destination_city_id'], unique=False)
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    op.create_index(op.f('ix_flights_origin_city_id'), 'flights', ['origin_city_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_activity_id'), 'reviews', ['activity_id'], unique=False)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_session_id'), 'reviews', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_session_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_activity_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_flights_origin_city_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_destination_city_id'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_collaboration_sessions_session_token'), table_name='collaboration_sessions')
    op.drop_index(op.f('ix_collaboration_sessions_expires_at'), table_name='collaboration_sessions')
    op.drop_table('collaboration_sessions')
    op.drop_index(op.f('ix_accommodations_id'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_city_id'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_category'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_avg_price_per_night'), table_name='accommodations')
    op.drop_table('accommodations')
    op.drop_index(op.f('ix_saved_itineraries_share_token'), table_name='saved_itineraries')
    op.drop_index(op.f('ix_saved_itineraries_session_id'), table_name='saved_itineraries')
    op.drop_index(op.f('ix_saved_itineraries_is_public'), table_name='saved_itineraries')
    op.drop_index(op.f('ix_saved_itineraries_created_at'), table_name='saved_itineraries')
    op.drop_table('saved_itineraries')
    # ### end Alembic commands ###
